name: 'LabelTest'
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'master'

jobs:
  job-a:
    name: Job A
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: echo ${{ steps.extract_branch.outputs.branch }}