name: 'LabelTest'
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'master'
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - id: isMaster
        run: echo ${GITHUB_REF_NAME}