name: 'create-load'
on:
  workflow_dispatch:
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  create:
    name: Test 1
    environment:
      name: hi
      url: ho
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - run: echo hello > test.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            *.txt
      - run: rm *.txt
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: test
      - run: ls -R
      - name: GitHub Wiki Action
        uses: Andrew-Chen-Wang/github-wiki-action@v4.4.0
      - run: ls -R

    
         
