name: 'load'
on:
  workflow_dispatch:

jobs:
  create:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: test
      - run: ls -R

         
