name: 'create-load'
on:
  workflow_dispatch:
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  create:
    name: Test 1
    environment:
      name: hi
      url: europe-west1-docker.pkg.dev/rd-itv-core-prod-bf93/itv-docker/itv-fpm-dev:php8.2-node18-pnpm7.9-add-bcmath
    runs-on: ubuntu-latest
    steps:
      - run: ls -R
      - run: echo hello
      - run: echo hello > test.txt
      - run: ls -R

    
         
